let TimelineData = [
  // {
  //   id: 1,
  //   title: "LongShot AI",
  //   link: "https://www.longshot.ai/",
  //   location: "Software Engineer Intern | Remote",
  //   desc1: "Spearheaded Vue.js development for Longshot AI’s website and also utilized React and TypeScript for their flagship product(Fulcrum)",
  //   desc2: "Achieved an 80% increase in user satisfaction by significantly improving app performance through data streaming and advanced frontend features, including pagination, infinite scroll, lazy loading, caching, analytics and auto scroll.",
  //   desc3: "Developed and delivered production-ready products involving GenAI models, and contributed to testing using Playwright for comprehensive automated testing.",
  //   date: "December 2023 - Present",
  //   icon: "work",
  // },
  // {
  //   id: 2,
  //   title: "Smart Indian Hackathon",
  //   link: "https://github.com/NyayaSetu-SIH/Dashboard",
  //   location: "SIH 2023 Finalist",
  //   desc1: "My Team NyaySetu participated in the Smart India Hackathon 2023 Grand Finale, held on December 19-20, 2023. Although we didn't clinch the top spot, the experience was nothing short of amazing!",
  //   desc2: "Not only did we learn invaluable skills, but we also had the chance to build lasting connections, explore the vibrant city of Kolkata, and engage with industry experts who shared their insights and wisdom. It was an experience that went beyond the competition itself.",
  //   date: "Dec 2023 - Dec 2023",
  //   icon: "school",
  // },
  // {
  //   id: 3,
  //   title: "LongShot AI",
  //   link: "https://www.longshot.ai/",
  //   location: "FrontEnd Developer Intern | Remote",
  //   desc1: "Excelled as a Frontend Developer Intern, where my expertise in Vue.js and proficiency with JavaScript were pivotal to my successful contributions to the team's development efforts.",
  //   desc2: "Showcased strong problem-solving skills and agility in learning, which enabled me to rapidly take on new tasks and deliver high-quality products within tight deadlines.",
  //   date: "June 2023 - Oct 2023",
  //   icon: "work",
  // },
  // {
  //   id: 4,
  //   title: "Programming Club, AKGEC",
  //   link: "https://pcakgec.tech/",
  //   location: "Senior Coordinator",
  //   desc1: "Coordinated and mentored numerous coding contests and workshops in collaboration with a team of 47 members.",
  //   desc2:"",
  //   date: "Apr 2022 - Present",
  //   icon: "work",
  // },
  {
    id: 3,
    title: "Chandigarh University",
    location: "Noida, India",
    desc1: "Masters in Computer Applications",
    desc2:"",
    date: "June 2021 - current",
    icon: "school",
  },
  {
    id: 5,
    title: "IMS Noida",
    location: "Noida, India",
    desc1:"Bachelors in Computer Applications",
    desc2: "Percentage:62% ",
    date: "July 2019- june 2022",
    icon: "school",
  },
  {
    id: 6,
    title: "Radiant Academy",
    location: "Noida, India",
    desc1:"Higher Secondary School, CBSE.",
    desc2:"Percentage : 82% (PCM)",
    buttonText: "College Projects",
    date: "2019",
    icon: "school",
  },
  {
    id: 7,
    title: "Radiant Academy",
    location: "Noida, India",
    desc1: "High School, CBSE.",
    desc2:"Grade : 7.2",
    date: "2017",
    icon: "school",
  },
];

export default TimelineData;